include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
